### ISSUE TITLE
[Documentation] Not able to build the toolchain from source.

### ISSUE THREAD

**Issue by sachinpatl** [webosbrew/native-toolchain#1]
I was able to build the toolchain but not able to Build Toolchain Port.

sachinp@sachinp-virtual-machine:~/webos_workspace/sdk_build$ cmake --build build 
CMake Error: Unknown argument --build
CMake Error: Run 'cmake --help' for all supported options.

Also cmake is not supporting --install flag.

Please help.

**Comment by mariotaku** [comment]
I'll need to update the docs indeed.

For Linux x86_64, prebuilt is available here: https://github.com/openlgtv/buildroot-nc4/releases/tag/webos-71307ba
For macOS x86_64, use port instead: https://github.com/webosbrew/native-toolchain/releases

Normally you don't need to build the whole SDK.
